name: product_d5
description: A sample command-line application with basic argument parsing.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.4

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  mysql1: ^0.19.1
  collection: ^1.16.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
